### PR TITLE
fix: don't fail on DROP ROLE IF EXISTS/ALTER TABLE RENAME

### LINKED ISSUE #10: reserved_role crashes causes segfault when renaming tables
# Bug report

## Describe the bug

If you enable `supautils.reserved_roles`, any attempts to rename a table via `ALTER TABLE` crash the database.

## To Reproduce

- Configure Postgres with supautils and set `supautils.reserved_roles` to a reserved role.
- Create a table
- Attempt to rename the table with `alter table` - postgres will crash.

For example:

Settings from postgresql.conf
```
# Add settings for extensions here
shared_preload_libraries = 'supautils'
supautils.reserved_memberships = 'pg_read_server_files,pg_write_server_files,pg_execute_server_program,pg_read_all_settings'
supautils.reserved_roles = 'user_a'
```

Users:
```
test=> \du
                                   List of roles
 Role name |                         Attributes                         | Member of
-----------+------------------------------------------------------------+-----------
 admin     | Create role, Create DB                                     | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 user_a    |                                                            | {}
```

Create a table and rename it:

```
[root@c2e4ce2e2625 supautils-1.1.0]# psql -U admin test
psql (12.7)
Type "help" for help.

test=> CREATE TABLE foo (id int);
CREATE TABLE
test=> ALTER TABLE foo RENAME TO bar;
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!>
```
Debug PG logs from the above:

```
2021-08-31 18:26:06.667 UTC [226] DEBUG:  CommitTransaction(1) name: unnamed; blockState: STARTED; state: INPROGRESS, xid/subid/cid: 0/1/0
2021-08-31 18:26:08.901 UTC [226] DEBUG:  StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0
2021-08-31 18:26:08.909 UTC [183] LOG:  server process (PID 226) was terminated by signal 11: Segmentation fault
2021-08-31 18:26:08.909 UTC [183] DETAIL:  Failed process was running: ALTER TABLE foo RENAME TO bar;
2021-08-31 18:26:08.909 UTC [183] LOG:  terminating any other active server processes
2021-08-31 18:26:08.910 UTC [220] WARNING:  terminating connection because of crash of another server process
2021-08-31 18:26:08.910 UTC [220] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
```

If I remove `supautils.reserved_roles` from the config, the rename statement works.

## Expected behavior

Renaming a table should not cause a segfault.

## System information

- OS: UBI 8
- Version of supabase: 1.1.0
- Version of Postgres 12.7 (hits other versions though)

### LINKED ISSUE #11: reserved_role breaks DROP ROLE IF EXISTS ....
# Bug report

## Describe the bug

If you enable `supautils.reserved_roles`, `DROP ROLE IF EXISTS ...` fails with SQLSTATE 42704 for non-existent users instead of skipping the `DROP USER`.

## To Reproduce

- Configure Postgres with supautils and set `supautils.reserved_roles` to a reserved role.
- run ` DROP ROLE IF EXISTS` for a non-existent user, it will return an error instead of skipping the drop - SQLSTATE 42704 

For example:

Settings from postgresql.conf
```
# Add settings for extensions here
shared_preload_libraries = 'supautils'
supautils.reserved_memberships = 'pg_read_server_files,pg_write_server_files,pg_execute_server_program,pg_read_all_settings'
supautils.reserved_roles = 'user_a'
```

```
psql -U admin test
psql (12.7)
Type "help" for help.

test=> \du
                                   List of roles
 Role name |                         Attributes                         | Member of
-----------+------------------------------------------------------------+-----------
 admin     | Create role, Create DB                                     | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 user_a    |                                                            | {}
 user_b    |                                                            | {}

test=> DROP ROLE IF EXISTS "user_b";
DROP ROLE
test=> \du
                                   List of roles
 Role name |                         Attributes                         | Member of
-----------+------------------------------------------------------------+-----------
 admin     | Create role, Create DB                                     | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 user_a    |                                                            | {}

test=> DROP ROLE IF EXISTS "user_b";
ERROR:  role "user_b" does not exist
```

Disabling the reserved_role settings allows it to work as intended:

```
psql -U admin test
psql (12.7)
Type "help" for help.

test=> \du
                                   List of roles
 Role name |                         Attributes                         | Member of
-----------+------------------------------------------------------------+-----------
 admin     | Create role, Create DB                                     | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 user_a    |                                                            | {}

test=> DROP ROLE IF EXISTS "user_b";
NOTICE:  role "user_b" does not exist, skipping
DROP ROLE
```

Debug logs from the failing DROP

```
2021-08-31 18:40:25.642 UTC [358] DEBUG:  CommitTransaction(1) name: unnamed; blockState: STARTED; state: INPROGRESS, xid/subid/cid: 0/1/0
2021-08-31 18:40:27.107 UTC [358] DEBUG:  StartTransaction(1) name: unnamed; blockState: DEFAULT; state: INPROGRESS, xid/subid/cid: 0/1/0
2021-08-31 18:40:27.107 UTC [358] NOTICE:  role "user_b" does not exist, skipping
2021-08-31 18:40:27.108 UTC [358] DEBUG:  CommitTransaction(1) name: unnamed; blockState: STARTED; state: INPROGRESS, xid/subid/cid: 0/1/0
2021-08-31 18:40:28.201 UTC [358] DEBUG:  shmem_exit(0): 1 before_shmem_exit callbacks to make
2021-08-31 18:40:28.201 UTC [358] DEBUG:  shmem_exit(0): 6 on_shmem_exit callbacks to make
2021-08-31 18:40:28.201 UTC [358] DEBUG:  proc_exit(0): 3 callbacks to make
2021-08-31 18:40:28.201 UTC [358] DEBUG:  exit(0)
2021-08-31 18:40:28.201 UTC [358] DEBUG:  shmem_exit(-1): 0 before_shmem_exit callbacks to make
2021-08-31 18:40:28.201 UTC [358] DEBUG:  shmem_exit(-1): 0 on_shmem_exit callbacks to make
2021-08-31 18:40:28.201 UTC [358] DEBUG:  proc_exit(-1): 0 callbacks to make
```

## Expected behavior

`DROP ROLE IF EXISTS ...` skip not error out if the role does not exist and role_protection is enabled. 

## System information

- OS: UBI 8
- Version of supabase: 1.1.0
- Version of Postgres 12.7 (hits other versions though)

### PR DESCRIPTION
**Pull request by steve-chavez**
- Closes #11: Don't use `get_rolespec_name()` on the DROP ROLE case because it validates that the ROLE exists before the standard hook can act and be lenient on DROP ROLE IF EXISTS.

- Closes #10: ALTER TABLE RENAME was failing, only catch ALTER ROLE RENAME statements and avoid processing other RENAME statements.

### CODE REVIEW

File: src/supautils.c [hunk 1]
```diff
@@ -368,15 +374,19 @@ look_for_reserved_role(Node *utility_stmt, List *roles_list)
 					RoleSpec *role = lfirst(item);
 					ListCell *role_cell;
 
-					// Break if the role is PUBLIC, let pg give a better error later
-					if (role->roletype == ROLESPEC_PUBLIC)
+					// Break if the role is PUBLIC, CURRENT_USER or SESSION_USER
+					// these cannot be used anyway because doing DROP ROLE CURRENT_USER
+					// makes pg fail with
+					// ERROR:  cannot use special role specifier in DROP ROLE
```
Comment (gurjeet) [inline src/supautils.c:380]: I think the comment can be worded a bit better. Perhaps like this:

```
/*
 * We check only for a named role being dropped; we ignore
 * the special values like PUBLIC, CURRENT_USER, and
 * SESSION_USER. We let Postgres throw its usual error messages
 * for those special values.
 */
```

File: src/supautils.c [hunk 2]
```diff
@@ -368,15 +374,19 @@ look_for_reserved_role(Node *utility_stmt, List *roles_list)
...
+					if (role->roletype != ROLESPEC_CSTRING)
 						break;
 
 					foreach(role_cell, roles_list)
 					{
 						char *reserved_role = (char *) lfirst(role_cell);
-
-						if (strcmp(get_rolespec_name(role), reserved_role) == 0)
+						// We don't use get_rolespec_name() here because it'll
+						// validate the role exists and will make DROP ROLE IF EXISTS fail
```
Comment (gurjeet) [inline src/supautils.c:388]: Similarly, this comment can be improved as:

```
/*
 * We extract the string from RoleSpec, instead of using get_rolespec_name(),
 * because that function does a syscache lookup, and that would fail for
 * non-existent roles. E.g when IF EXISTS clause is being used, which is not
 * supposed to ERROR on non-existent roles. We leave handling of
 * non-existent roles up to Postgres.
 */
```

**Review by gurjeet — APPROVED** [review]

**Review by olirice — APPROVED** [review]

File: src/supautils.c (hunk 2 above)
Comment (steve-chavez) [reply src/supautils.c]: These are great comments :100: , I've just added them. Thanks Gurjeet!
